# Generated by Django 4.2.27 on 2026-02-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Marque')),
                ('model', models.CharField(max_length=100, verbose_name='Modèle')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('year', models.IntegerField(verbose_name='Année')),
                ('kilometrage', models.IntegerField(default=0, verbose_name='Kilométrage')),
                ('fuel', models.CharField(choices=[('Essence', 'Essence'), ('Diesel', 'Diesel'), ('Hybride', 'Hybride'), ('Electrique', 'Électrique')], default='Essence', max_length=20, verbose_name='Carburant')),
                ('transmission', models.CharField(choices=[('Manuelle', 'Manuelle'), ('Automatique', 'Automatique')], default='Manuelle', max_length=20, verbose_name='Boîte de vitesse')),
                ('city', models.CharField(default='Yaoundé', max_length=100, verbose_name='Ville')),
                ('status', models.CharField(choices=[('Disponible', 'Disponible'), ('Vendu', 'Vendu'), ('En attente', 'En attente de validation')], default='En attente', max_length=20, verbose_name='Statut')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Photo principale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
